### ISSUE TITLE
https://sbft24.github.io/tools/ Fuzzing Competition

### ISSUE THREAD

**Issue by vrthra** [sbft24/sbft24.github.io#13]
Could you please remove the old content on Fuzzing Competition from this page (blurb, slides, and video)

The new blurb will be

Continuing from previous year, we will hold a Fuzzing Tool competition. We will be using mutation analysis (https://arxiv.org/abs/2212.03075) integrated into fuzzbench as a benchmarking tool for the fuzzers. The details on how to submit your fuzzer can be found [here](https://sbft24.github.io/tools/fuzzing).

The picture of fuzzbench should be kept.

The infrastructure for the fuzzing competition is provided by [Google](https://www.google.com) (Fuzzbench) and [University of Sydney School of Computer Science](https://www.sydney.edu.au/engineering/schools/school-of-computer-science.html)

**Comment by alessiogambi** [comment]
Related to #8

**Comment by rrtorrubiano** [comment]
done
