### ISSUE TITLE
CPS-UAV inputs for the sbft web page.

### ISSUE THREAD

**Issue by spanichella** [sbft24/sbft24.github.io#14]
As requested by [@Alessio Gambi], both  [@Sajad Khatiri] and I worked on the inputs from the CPS-UAV competition, you find the inputs to put in the web page (at this page https://sbft24.github.io/tools/) at the following g-doc: https://docs.google.com/document/d/1kqGQMJVnaSLXgYzNA6lWZvi4-Y6_L6BVI0ffwzfgT8w/edit?usp=sharing Please let us know if anything is not clear (or when you have updated the page, so we can promote it on social media).

**Comment by rrtorrubiano** [comment]
done
