### ISSUE TITLE
Python inputs for the sbft web page

### ISSUE THREAD

**Issue by spanichella** [sbft24/sbft24.github.io#15]
As requested by [@alessio Gambi], all Python co-chairs worked on the inputs of the Python competition, you find the inputs to put in the web page:
- (at this page https://sbft24.github.io/tools/) at the following g-doc: https://docs.google.com/document/d/19hgHYjcfriHRbqcYQDLaQn7XI3PMkVKMdZp9dqOdHJc/edit?usp=sharing
- (at this page https://sbft23.github.io/tools/python) at the following g-doc: 
- https://docs.google.com/document/d/1-cdCNy1mhEUfq_BW9n4me1ctetUk8lxC3RXdKK-89aA/edit?usp=sharing  

 if anything is not clear (or when you have updated the page, so we can promote it on social media).

**Comment by rrtorrubiano** [comment]
done
