### ISSUE TITLE
Tool competition page CPS-Self-driving cars

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#18]
The page says:

**CPS**: notify the organizers by sending an email to Vincenzo Riccio, Matteo Biagiola, Stefan Klikovits, Jarkko Peltomäki ([vincenzo.riccio@usi.ch, matteo.biagiola@usi.ch, stefan@klikovits.net, jarkko.peltomaki@abo.fi](mailto:vincenzo.riccio@usi.ch,%20matteo.biagiola@usi.ch,%20stefan@klikovits.net,%20jarkko.peltomaki@abo.fi)).```

We should make it uniform with the other tools competitions and remove those who are not part of the organization anymore. Better to update it to:

**CPS**: notify the <a href="mailto:matteo.biagiola@usi.ch;stefan@klikovits.net?subject=SBFT2024 CPS Competition">organizers</a> and follow the instructions provided [here](https://github.com/sbft-cps-tool-competition/cps-tool-competition).

**Comment by alessiogambi** [comment]
Actually, there's more to it. I see that below the bullet points, we have a repetition of the thing, that is inconsistent. Maybe there's a way to make it more uniform?

**Comment by alessiogambi** [comment]
According to @Matteo Biagiola, there's no need for registration. So we can simply point say:

**CPS**: follow the instructions provided [here](https://github.com/sbft-cps-tool-competition/cps-tool-competition).

**Comment by rrtorrubiano** [comment]
done
