### ISSUE TITLE
Navbar buttons uncentered

### ISSUE THREAD

**Issue by rrtorrubiano** [sbft24/sbft24.github.io#21]
The buttons on the navbar look a bit awkward after adding two new items. The text is now two-lined (it was one-lined before) and it should be centered. As I'm no css expert, would be nice to have someone with more css background look at this.
<img width="844" alt="image" src="https://github.com/sbft24/sbft24.github.io/assets/61320494/aa0c7cd1-5900-4f21-b2f7-1a50a72d227e">

**Comment by checkdgt** [comment]
@rrtorrubiano .. I'll take a look .. depends on how we want this to look too .. I guess having it icon and then text (2 line) underneath? If you resize the browser window then you'll see it like the image attached. This could be cleaner with some centering too, but would look good for the larger screen size as well.
![Screenshot 2023-10-05 at 13 05 24](https://github.com/sbft24/sbft24.github.io/assets/8478412/94125a02-5d77-4e26-b02d-51f312764ece)

**Comment by rrtorrubiano** [comment]
Hi @checkdgt! I switched to your fix branch and it looks good there (icon and centered text underneath). You can merge your fix with the main branch imho. Thanks!

**Comment by rrtorrubiano** [comment]
FYI @checkdgt I just merged the branch.
