### ISSUE TITLE
Tutorial Update

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#22]
@rrtorrubiano  Hi, we got new data for the tutorial by CISPA. Could you add that to the tutorial page?

First part of the tutorial:

Title: Fuzz Testing for Security
Abstract: In this talk, I will give an overview of our recent results in randomized testing ("fuzzing") and present some of the techniques we have developed in recent years. These include fuzzing complex software systems such as operating system kernels, hypervisors, and interpreters using various testing methods. I will also discuss how fuzzing relates to games such as Super Mario Bros. or Sokoban.

Second part of the tutorial:

Title: SoKotHban: A King-of-the-Hill-style Search Optimisation
Competition
Abstract: Sokoban, a puzzle game developed in the early 1980s, has
proven to be a challenging search optimisation problem often aligned
with autonomous agent research. The eponymous "warehouse keeper"
attempts to move crates into desired positions, often encountering
difficult terrain and situations as crates the players themselves have
moved block the path. These puzzles prove to be difficult for humans
and computers alike, and general-purpose solving for Sokoban puzzles is
PSPACE-complete as shown by previous research. To improve the academic
understanding of the problem, we propose a King-of-the-Hill (KotH)
competition in which competitors develop both automated puzzle solvers
and generators. With this, we hope to identify what puzzle features
weaken which optimisation strategies, what strategies can be used to
defeat new challenges, and observe specialised adversarial techniques
to target and disrupt tactics employed by various competitors.

**Comment by alessiogambi** [comment]
We also have a confirmation that there will be a second tutorial by Annibale Panichella:
Annibale Panichella, TU Delft, Netherlands

**Comment by rrtorrubiano** [comment]
Hi @alessiogambi, who is the author of the first tutorial? And should I already include Annibale in the tutorials page or wait until there is a tutorial description?

**Comment by alessiogambi** [comment]
@rrtorrubiano The authors of the first tutorial are Thorsten Holz and Addison Crump, CISPA, Germany

- Thorsten Holz will do the First part of the tutorial
- Addison Crump will do the Second part

Please, also include Annibale's tutorial, with Title, Bio, Abstract as "Coming Soon"

When the page is updated, I'll remind Annibale

**Comment by rrtorrubiano** [comment]
Changes done. If Thorsten or Addison want to have a pic, please notify me.
