### ISSUE TITLE
Submission link update

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#23]
@checkdgt or @rrtorrubiano 
We have the submission link. Could you please add it to the web page?

https://sbft2024.hotcrp.com/

**Comment by checkdgt** [comment]
@alessiogambi 
Should this link supersede the current link on the site?
"https://easychair.org/my/conference?conf=sbft2024"

**Comment by alessiogambi** [comment]
@checkdgt The EasyChair link never existed, it was a left over from the last year ;)
