### ISSUE TITLE
Discussion Panel Update

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#24]
We have the following five confirmed panelists. Could you add them to https://sbft24.github.io/panel/?

Please, use last year format as template: https://sbft23.github.io/panel/

Panelist:
* Jim Whitehead,  University of California, Santa Cruz, USA
* Caroline Lemieux, University of British Columbia, Canada
* Mark Harmann, Meta & University College London, UK
* Jie Zhang, King’s College London, UK
* Andreas Zeller, CISPA, Germany

**Comment by p1ndsvin** [comment]
Added the panelists, please add the pictures

**Comment by checkdgt** [comment]
Added the pictures

**Comment by rrtorrubiano** [comment]
issue can be closed
