### ISSUE TITLE
Kenote page does not show the images of the speakers

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#26]
https://sbft24.github.io/keynotes/

**Comment by alessiogambi** [comment]
We should add a link to their personal web page as well. This was done for the panelists of last year edition, but we should do it for all the invited/guest speakers

**Comment by checkdgt** [comment]
Do we have a document that contains their personal web page or do we need to look this up for each panelist?

**Comment by p1ndsvin** [comment]
We do not have that document. For the panel, I added the personal webpage by looking on Google. The images should be stored in https://github.com/sbft24/sbft24.github.io/tree/main/img
