### ISSUE TITLE
https://sbft23.github.io/tools/fuzzing Prices

### ISSUE THREAD

**Issue by vrthra** [sbft24/sbft24.github.io#40]
Hi, since Google has confirmed that they would consider integrated fuzzers for prices, could we please put back the original prices heading?

## Prizes and awards

Top-performing participants will be eligible to be considered for a new OSS-Fuzz [FuzzBench integration reward](https://bughunters.google.com/about/rules/5097259337383936/oss-fuzz-reward-program-rules) (up to $11,337, depending on impact).

**Comment by checkdgt** [comment]
Have re-added this.
