### ISSUE TITLE
Fuzzing competition Registration date is wrong

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#42]
Currently, the page ```https://sbft24.github.io/tools/fuzzing``` says:

```Express your interest [here](https://forms.gle/pwxtqgEaN724NESC9) (Deadline: AoE Friday 01 Dec 2024).```

It should be

```Express your interest [here](https://forms.gle/pwxtqgEaN724NESC9) (Deadline: AoE Friday 01 Dec 2023).```

**Comment by checkdgt** [comment]
My bad, I must have been thinking too far ahead :) .. fixed.
