### ISSUE TITLE
The to the formatting instructions according to ICSE2024 is wrong

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#43]
Currently, the home page shows this message:

![image](https://github.com/sbft24/sbft24.github.io/assets/1557512/51059b6b-44ed-4d99-8cc4-83c62e59b5bb)

And the "ICSE’24 formatting and submission instructions `https://conf.researchr.org/track/icse-2024/icse-2024-technical-track#About`

However, we use HotCRP not EasyChair, and the link to the formatting instructions should be:
`https://conf.researchr.org/track/icse-2024/icse-2024-research-track#Call-for-papers`

**Comment by checkdgt** [comment]
I updated the top part but missed this last time, have updated.
