### ISSUE TITLE
In the organization page, we should add names of confirmed PC members and the link to the self-registration form

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#44]
The link to the PC self-nomination form is:
```https://forms.gle/wHf5Do55JTJdkuFK8```

The confirmed names of PC are the following.

### Research Track:

Name | Surname | Affiliation
-- | -- | --
Aymeric | Blot | University of Rennes
Byron | DeVries | Grand Valley State University
Erik | Fredericks | Grand Valley State University
Gregory | Gay | Chalmers and University of Gothenburg
Gregory | Kapfhammer | Department of Computer and Information Science, Allegheny College
Kate | Bowers | Oakland University
Ruben | Ruiz-Torrubiano | IMC Krems University of Applied Sciences
Silvia Regina | Vergilio | UFPR
Thomas | Vogel | Humboldt-Universität zu Berlin, Germany

### Education Track:

Name | Surname | Affiliation
-- | -- | --
Filomena | Ferrucci | University of Salerno, Italy
Florian | Obermueller | University of Passau
João Pascoal | Faria | University of Porto & INESC TEC
José Miguel | Rojas | The University of Sheffield, UK
Philipp | Straubinger | University of Passau
Porfirio | Tramontana | University of Naples Federico II
Raquel | Blanco | University of Oviedo
Sarita | Paudel | IMC University of Applied Sciences, Austria

**Comment by alessiogambi** [comment]
@rrtorrubiano No need to have pictures for the PC Members.

**Comment by rrtorrubiano** [comment]
Done
