### ISSUE TITLE
Keynote Info Update

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#50]
The following is the information Gordon provided about the Keynote to publish on the web site:

Title: Search-based Testing and Analysis for Block-Based Learners’ Programs

Abstract: Programming is increasingly taught using dedicated block-based programming environments such as Scratch. While the use of blocks instead of text prevents syntax errors, learners can still make semantic mistakes, implying a need for feedback and help. Professional programmers can receive such support from efficient program analyses built into their IDEs, but block-based programming environments offer no such support. In this talk, I will describe some of our efforts to remedy this issue, which are based on search-based testing at the core. The colourful and small nature of learners’ programs is deceiving, as the game-like, highly concurrent and event-driven nature of the programs poses unique challenges for these analyses.

**Comment by checkdgt** [comment]
Keynote added :)
