### ISSUE TITLE
Update info on tutorials

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#56]
We have the details of the second tutorial (see below). Can you update the tutorials page? Thanks!

*Title*: Getting Started with SynTest-Framework: A Hands-on Tutorial for Automatic Test Case Generation and Fuzzing

*Speakers*: Mitchell Olsthoorn and Annibale Panichella
 
*Summary*: SynTest-Framework is a user-friendly, modular, and highly extensible ecosystem for automatic test case generation and fuzzing. Its architecture allows testing tools for different programming languages to be built on top of it. Additionally, the framework contains a collection of language-independent search algorithms that are optimized for automatic test case generation and fuzzing. Our main goal with the framework is to make it easier for researchers to implement new approaches for automatic test case generation. Additionally, we hope that the framework will make it easier for practitioners to adopt automatic test case generation in their projects.
 
In this tutorial session, we will show how to use the framework to implement a new automatic test case generation approach. Furthermore, we will also show how to use the framework to implement a new testing tool. The tutorial will be hands-on and will consist of a series of practical scenarios. These scenarios will be based on the TypeScript programming language. Join us in this fun and interactive tutorial session and equip yourself with the skills to demonstrate your approach to software testing and validation.

**Comment by checkdgt** [comment]
Done.
