### ISSUE TITLE
Organization Page:

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#6]
Workshop Co-Chairs: Alessio Gambi, Gunel Jahangirova, and Vincenzo Riccio (new affiliation, University of Udine)

Competition Co-Chairs:
Matteo Biagiola, Stefan Klikovits, Valerio Terragni, Sajad Khatiri, Christian Birchler, Sebastiano Panichella, Jose Campos, Rahul Gopinath, and many more...

**Comment by alessiogambi** [comment]
Website Chair:
Ruben Ruiz Torrubiano

**Comment by alessiogambi** [comment]
Virtualisation Support & Student Volunteer: Remove this section for the moment

**Comment by rrtorrubiano** [comment]
done
