### ISSUE TITLE
Add BeamNG as sponsor to web page

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#62]
@checkdgt or @rrtorrubiano could you please add BeamNG logo to the web page and post about their support on X? (@beamng)

Thanks!

<img width="529" alt="GMBH-Logo" src="https://github.com/sbft24/sbft24.github.io/assets/1557512/630388c5-ac48-47ee-958e-b9edba855760">

**Comment by checkdgt** [comment]
Added.
