### ISSUE TITLE
Add keynote

### ISSUE THREAD

**Issue by p1ndsvin** [sbft24/sbft24.github.io#63]
**Speaker:** Anna Rita Fasolino, University of Naples Federico II, Italy
**Title:** Beyond the Class: A look into current trends in software testing education
**Abstract:** Software testing is indispensable in software development, yet often overlooked, contributing to a shortage of expertise in the software industry. Despite efforts to improve teaching approaches at the university level, challenges persist, particularly in bridging the gap between theory and practice and better preparing students for their future careers.
This talk will provide a closer look at how software testing is taught at the academic level, considering the perspectives of students and teachers. I will describe the most common challenges that students experience when taking a software testing course. 
Then, I give voice to teachers, reporting the approaches they usually adopt in software testing courses and the challenges they face. Emerging initiatives like gamification and challenge-based learning are potential solutions to fill the gaps between the teachers’ efforts and students’ needs.

**Comment by checkdgt** [comment]
I've added her to the keynotes .. I'm not sure if there's an order to them, so far they're top to bottom as I've added them.
