### ISSUE TITLE
Program Committee

### ISSUE THREAD

**Issue by alessiogambi** [sbft24/sbft24.github.io#7]
The Program Committee must be updated
The Education Track Program Committed must be added

**Comment by rrtorrubiano** [comment]
@alessiogambi  where do I find the members?

**Comment by alessiogambi** [comment]
@rrtorrubiano At the moment, we are in the process of forming the PC. We'll notify you soon. For the moment, it is ok to remove the old data and replace it with something like (Coming Soon)

**Comment by rrtorrubiano** [comment]
ok, done. But I don't quite understand yet which changes need to be done for the Education Track. I understand this track is new. Should I add a new Education Co-Chairs section within the Organisation page? New submenu in the navigation bar?

**Comment by alessiogambi** [comment]
Thanks.
> Should I add a new Education Co-Chairs section within the Organisation page?

Yes. For the Co-Chairs, we have [Annarita Fasolino](https://www.researchgate.net/profile/Anna-Fasolino) and Vincenzo Riccio. More names will come soon.

> New submenu in the navigation bar?

Yes

**Comment by rrtorrubiano** [comment]
done
